import Div from '../../components/Div';
import Head from 'next/head';
import dynamic from 'next/dynamic';
import Word from "../../components/Word";
import { useState } from "react";

const CustomCursor = dynamic(
    () => {
      return import('../../components/CustomCursor');
    },
    { ssr: false },
);

export default function AI() {
    const [word] = useState("Hello");
    const [valiny] = useState("Valiny");
    const [clicked, setClicked] = useState(false);

    const hello = ()=>{
        let sphere = document.getElementById("sphere");
        if(!clicked){
            sphere.style = "animation: slide-left 1000ms forwards;"; 
        } else {
            sphere.style = "animation: slide-restore 1000ms forwards;";
        }
        setClicked(!clicked);
    }

    return(
        <>
            <Head>
                <title>AI Onirix</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <CustomCursor />
            
            <Div className="onirix" >
                <Div className="bg-image"></Div>
                <Div id="sphere" className="sphere">
                    <Word word={word} predict={hello}/>
                    {/* <Word word={word} predict={hello}/> */}
                </Div>
                {clicked && (
                    <Div className="answer">
                        <h5 className='text-center'>Prediction de votre reve</h5>
                        <p>{valiny}</p> 
                    </Div>
                )}
            </Div>
        </>
    )
}